version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: dindoa
    main: ./cmd/dindoa/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: dindoa
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - name_template: "dindoa-{{.Version}}-{{.Os}}-{{.Arch}}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: torreirow
    name: dindoa
  draft: false
  prerelease: auto
